### ISSUE TITLE
Code block runs infinitely

### ISSUE THREAD

**Issue by jakecminihan** [tillahoffmann/obsidian-jupyter#17]
I'm sorry to raise an issue as it's almost certainly my fault, but I'm not sure what is wrong or how to fix it! I've attached images showing the output here - essentially, the problem is that it just infinitely runs and from the console messages, I can't really figure out what the error is. My python is v3.9 and my jupyter dependencies are as follows:
![Screenshot_11](https://user-images.githubusercontent.com/62210689/135690916-883a3156-0354-4153-8c44-5cf00ed1ab33.jpg)

Error logs/screenshots:
![Screenshot_9](https://user-images.githubusercontent.com/62210689/135690948-b7ab019e-71f0-46db-b87c-499cdc470c8c.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/62210689/135690955-eeb19fbf-38fc-45da-9aa7-d37fc638234b.jpg)

I've got no other plugins running at this time, Obsidian is the newest version too. Thank you so much!

**Comment by tillahoffmann** [comment]
It looks like your `nbconvert` is outdated (version 6 or newer is required). See [here](https://github.com/tillahoffmann/obsidian-jupyter#installation) for the minimum requirements. I'll close for now, but feel free to raise any issues should you still have problems after updating the python dependencies.

**Comment by jakecminihan** [comment]
I've updated my version of nbconvert to 6.2.0 so it should be OK, but I'm still getting the problem; obsidian output below:

```
main.ts:139 created new client for doc 608a7091dc4f00d2
main.ts:48 INFO:obsidian-jupyter:started server for document 608a7091dc4f00d2

main.ts:48 INFO:obsidian-jupyter:received request: {"id":"398d1e69-5bcc-47ba-954b-7583acf4057c","body":{"command":"execute","source":"\nprint(\"Hello, world!\")\n"}}


main.ts:48 C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\zmq\_future.py:591: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  self._get_loop()

main.ts:48 INFO:traitlets:Executing notebook with kernel: 

main.ts:48 INFO:obsidian-jupyter:shutting down kernel...

main.ts:48 Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\traitlets\traitlets.py", line 537, in get

main.ts:48     value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Jake\Documents\MSc Obsidian Notes\MSc Work\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 48, in <module>

main.ts:48     html_exporter = HTMLExporter(template_name='basic')
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 329, in __init__

main.ts:48     super().__init__(config=config, **kw)
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\exporter.py", line 114, in __init__

main.ts:48     self._init_preprocessors()
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 496, in _init_preprocessors

main.ts:48     conf = self._get_conf()
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 514, in _get_conf

main.ts:48     for path in map(Path, self.template_paths):
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\traitlets\traitlets.py", line 577, in __get__

main.ts:48     return self.get(obj, cls)
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\traitlets\traitlets.py", line 540, in get

main.ts:48     default = obj.trait_defaults(self.name)
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\traitlets\traitlets.py", line 1580, in trait_defaults

main.ts:48     return self._get_trait_default_generator(names[0])(self)
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\traitlets\traitlets.py", line 977, in __call__

main.ts:48     return self.func(*args, **kwargs)
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 525, in _template_paths

main.ts:48     template_names = self.get_template_names()
  File "C:\Users\Jake\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 607, in get_template_names

main.ts:48     raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'basic' found in the following paths:
	C:\Users\Jake\AppData\Roaming\jupyter
	C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\share\jupyter
	C:\ProgramData\jupyter
```
It does mention nbconvert a few times, but I'm not sure what's going wrong. Thank you for the help!

**Comment by tillahoffmann** [comment]
Could you post the output of `pip freeze` please?

**Comment by jakecminihan** [comment]
Of course! Here's the output:

```
anyio==3.3.2
argon2-cffi==21.1.0
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
basemap @ file:///D:/Users/Jake/Downloads/basemap-1.2.2-cp39-cp39-win_amd64.whl
bleach==4.1.0
certifi==2020.12.5
cffi==1.14.6
charset-normalizer==2.0.6
colorama==0.4.4
cycler==0.10.0
debugpy==1.4.3
decorator==5.1.0
defusedxml==0.7.1
entrypoints==0.3
idna==3.2
ipykernel==6.4.1
ipython==7.28.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.0
Jinja2==3.0.1
json5==0.9.6
jsonschema==4.0.1
jupyter==1.0.0
jupyter-client==7.0.5
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyter-server==1.11.0
jupyterlab==3.1.14
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.1
MarkupSafe==2.0.1
matplotlib==3.3.3
matplotlib-inline==0.1.3
mistune==0.8.4
nbclassic==0.3.2
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.4
numpy==1.19.4
packaging==21.0
pandocfilters==1.5.0
parso==0.8.2
pickleshare==0.7.5
Pillow==8.0.1
prometheus-client==0.11.0
prompt-toolkit==3.0.20
pycparser==2.20
Pygments==2.10.0
pyparsing==2.4.7
pyproj==3.0.0.post1
pyrsistent==0.18.0
pyshp==2.1.2
python-dateutil==2.8.1
pytz==2021.3
pywin32==301
pywinpty==1.1.4
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.2
requests==2.26.0
requests-unixsocket==0.2.0
Send2Trash==1.8.0
six==1.15.0
sniffio==1.2.0
terminado==0.12.1
testpath==0.5.0
tornado==6.1
traitlets==5.1.0
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
widgetsnbextension==3.5.1
```

I tried doing `pip install xxx -U` for some packages and it completely corrupted my Python installation and required a full reinstall. I think this issue might be one with my installation. Perhaps something to do with permissions, although it's installed on the default path. Thank you for all the help!

**Comment by tillahoffmann** [comment]
Interesting, it looks like something is awry with your installation, and nbconvert cannot find the templates directory. E.g. for my installation.

```
$ jupyter --paths
config:
    /Users/till/.jupyter
    /Users/till/.pyenv/versions/3.8.10/envs/python38/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/till/Library/Jupyter
    /Users/till/.pyenv/versions/3.8.10/envs/python38/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/till/Library/Jupyter/runtime
```

nbconvert will try to find templates within the listed paths (I *think* only the `data` paths, but not entirely sure). Investigating these paths further, I find:

```
$ls /Users/till/.pyenv/versions/3.8.10/envs/python38/share/jupyter/nbconvert/templates
asciidoc      classic       lab           python        script
base          compatibility latex         reveal        webpdf
basic         html          markdown      rst
```

So there is a `basic` template which this plugin will use to get the output. It seems like that is missing from your installation.
