### ISSUE TITLE
Need Help - isn't working on windows

### ISSUE THREAD

**Issue by XenonDerMico** [tillahoffmann/obsidian-jupyter#18]
**Before raising an issue**
I installed Python from https://www.python.org/downloads/windows/
exactly: https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe

**Describe the bug**
I tried: python -c 'import sys; print(sys.executable)'
but didn't work in CMD (Windows 10)
I tried: pip install jupyter --upgrade
that worked

In Obsidian, options, Jupyter plugin, Python interpreter:
I tried
C:/Users/...
C://Users/...
C:\Users\...
C:\\Users\\...
non of them worked

I can press "Run", which will change to "Running..." but will not terminate.

I hope it is just a stupid error and easy to fix.
Do you know what I can do?

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/1577065/136821953-9fcbe611-9aec-47d8-81a2-e6fbcf27f5bf.png)
![Screenshot_1](https://user-images.githubusercontent.com/1577065/136821956-3b74e5b8-ccd3-4f42-9374-af719e1e0b50.png)
![Screenshot_2](https://user-images.githubusercontent.com/1577065/136821958-80a562b8-9536-40a4-8b87-c162b8911ed5.png)

**Console output**
non

**Python dependencies**
![Screenshot_4](https://user-images.githubusercontent.com/1577065/136822151-a1a60153-4587-46e5-a1fe-16bc8b4f0b22.png)

**Comment by tillahoffmann** [comment]
Could you please post the output from the developer console? See [here](https://forum.obsidian.md/t/how-to-access-the-console/16703) on how to access it.

**Comment by XenonDerMico** [comment]
**Without Admin:**

main.ts:38 WARNING: Neo4j Graph View is deprecated and replaced by the new Obsidian plugin Juggl.
main.ts:157 Initializing Neo4j stream
main.ts:66 Loading Juggl
image-server.ts:79 Image server listening on http://localhost:3837/
main.ts:24 Supercharged links loaded
main.ts:13 Loaded Timelines Plugin
VM164:15166 Loaded Gallery Plugin
main.ts:27 loading markdown-table-editor plugin
main.ts:200 Obsidian Admonition loaded
app.js:1 [Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
(anonymous) @ app.js:1
main.ts:23 Loading Autocomplete plugin.
main.ts:28 Loading Day Planner plugin
VM172:35 loading dictionary
main.ts:82 loading FileExplorerNoteCount
main.ts:30 Loading Folder Note plugin.
main.ts:32 ledger: Loading plugin v0.0.8
main.ts:167 loading python lab plugin
main.ts:14 loading search-on-internet
main.ts:145 loading jupyter plugin
main.ts:162 python script exists at E:\Dokumente\My Mind\Support AI/.obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py
file.ts:76 Error: ENOENT: no such file or directory, open 'E:\Dokumente\My Mind\Support AI\Day Planners\Day Planner-20211017.md'
planner-md.ts:47 TypeError: Cannot read property 'split' of undefined
    at PlannerMarkdown.parseDayPlanner (eval at <anonymous> (app.js:1), <anonymous>:6142:83)
    at async eval (eval at <anonymous> (app.js:1), <anonymous>:7261:41)
main.ts:104 TypeError: Cannot read property 'calculate' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:7262:33)
localhost:5000/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.ts:161 Object
main.ts:165 
main.ts:173 
events.js:292 Uncaught Error: listen EADDRINUSE: address already in use :::3837
    at Server.setupListenHandle [as _listen2] (net.js:1318)
    at listenInCluster (net.js:1366)
    at Server.listen (net.js:1452)
    at Neo4jViewPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:81925:36)
    at step (eval at <anonymous> (app.js:1), <anonymous>:93:23)
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:74:53)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:67:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:63:12)
    at Neo4jViewPlugin.httpServer (eval at <anonymous> (app.js:1), <anonymous>:81878:16)
main.ts:191 Uncaught Error: ModuleNotFoundError: No module named 'smdc'
    at PythonShell.parseError (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:81463:21)
    at terminateIfNeeded (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:81347:32)
    at ChildProcess.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1215379), <anonymous>:81339:13)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    ----- Python Traceback -----
    File "E:\SYSTEM\TEMP\pythonShellFile5437280119.py", line 1, in <module>
      from smdc.stream import main;main();
122app.js:1 Uncaught TypeError: VizId.fromPath is not a function
    at eval (eval at <anonymous> (app.js:1), <anonymous>:507:37)
    at t.e.tryTrigger (app.js:1)
    at t.e.trigger (app.js:1)
    at t.trigger (app.js:1)
    at t.onChange (app.js:1)
    at e.trigger (app.js:1)
    at e.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
app.js:1 Uncaught (in promise) Error: Destination file already exists!
    at e.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
main.ts:139 created new client for doc 6cbf412c6b0e10c0
main.ts:48 Traceback (most recent call last):
  File "E:\Dokumente\My Mind\Support AI\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 3, in <module>

main.ts:48     from jupyter_client import KernelManager
ModuleNotFoundError: No module named 'jupyter_client'


**With Admin:**
![Screenshot_1](https://user-images.githubusercontent.com/1577065/137619227-947007f6-9468-4725-8f50-577bf0b6bee4.png)

**Comment by tillahoffmann** [comment]
The [required dependencies](https://github.com/tillahoffmann/obsidian-jupyter#installation) are not installed for the interpreter you're using.

**Comment by tillahoffmann** [comment]
Try upgrading to 0.5.0 and use the `Install requirements` button in the settings.

**Comment by XenonDerMico** [comment]
**I updated to 0.5.0 and used Install requirements.**

**now I have: Console:**

```
Loading Juggl
image-server.ts:79 Image server listening on http://localhost:3837/
main.ts:24 Supercharged links loaded
main.ts:13 Loaded Timelines Plugin
VM259:15166 Loaded Gallery Plugin
main.ts:27 loading markdown-table-editor plugin
main.ts:200 Obsidian Admonition loaded
app.js:1 [Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
main.ts:23 Loading Autocomplete plugin.
main.ts:28 Loading Day Planner plugin
VM267:35 loading dictionary
main.ts:82 loading FileExplorerNoteCount
main.ts:30 Loading Folder Note plugin.
main.ts:32 ledger: Loading plugin v0.0.8
main.ts:14 loading search-on-internet
main.ts:145 loading jupyter plugin
main.ts:162 python script exists at E:\Dokumente\My Mind\Support AI/.obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py
main.ts:139 created new client for doc 5c0558d6239c5f5c using interpreter C:/Users/###/AppData/Local/Programs/Python/Python310/python.exe
main.ts:48 C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\session.py:47: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from zmq.eventloop.ioloop import IOLoop

main.ts:48 INFO:obsidian-jupyter:started server for document 5c0558d6239c5f5c

main.ts:48 INFO:obsidian-jupyter:received request: {"id":"ff9b822b-eb0e-4031-bd12-e5c684e79104","body":{"command":"execute","source":"print(\"FOO\")\nprint(\"sdad\")\n"}}


main.ts:48 INFO:obsidian-jupyter:shutting down kernel...

main.ts:48 Traceback (most recent call last):
  File "E:\Dokumente\My Mind\Support AI\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 45, in <module>

main.ts:48     nb = client.execute(nb)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 78, in wrapped

main.ts:48     return just_run(coro(*args, **kwargs))
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 57, in just_run

main.ts:48     return loop.run_until_complete(coro)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete

main.ts:48     return future.result()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 542, in async_execute

main.ts:48     async with self.async_setup_kernel(**kwargs):
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__

main.ts:48     return await anext(self.gen)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 500, in async_setup_kernel

main.ts:48     await self.async_start_new_kernel(**kwargs)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 412, in async_start_new_kernel

main.ts:48     await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 20, in wrapped

main.ts:48     nest_asyncio.apply(loop)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 21, in apply

main.ts:48     _patch_tornado()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 202, in _patch_tornado

main.ts:48     import tornado.concurrent as tc
ModuleNotFoundError: No module named 'tornado.concurrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

main.ts:48   File "E:\Dokumente\My Mind\Support AI\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 67, in <module>

main.ts:48     km.shutdown_kernel()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped

main.ts:48     raise e
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped

main.ts:48     return loop.run_until_complete(future)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:48     return f.result()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result

main.ts:48     raise self._exception
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step

main.ts:48     result = coro.send(None)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 434, in _async_shutdown_kernel

main.ts:48     await ensure_async(self.interrupt_kernel())
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped

main.ts:48     raise e
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped

main.ts:48     return loop.run_until_complete(future)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:48     return f.result()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result

main.ts:48     raise self._exception
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step

main.ts:48     result = coro.send(None)
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 542, in _async_interrupt_kernel

main.ts:48     raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
```

**Comment by tillahoffmann** [comment]
Could you please post the console output provided when you press the `Install requirements` button?

**Comment by XenonDerMico** [comment]
**This is only "Install dependencies". Or do you mean something else? **

```
main.ts:290 install stdout: Requirement already satisfied: jupyter in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
Requirement already satisfied: notebook in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.5)
Requirement already satisfied: qtconsole in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (5.1.1)
Requirement already satisfied: jupyter-console in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.0)
Requirement already satisfied: ipywidgets in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (7.6.5)
Requirement already satisfied: ipykernel in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.2)
Requirement already satisfied: nbconvert in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.2.0)
Requirement already satisfied: ipython-genutils in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (0.2.0)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (1.5.1)
Requirement already satisfied: traitlets<6.0,>=4.1.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (5.1.0)
Collecting traitlets<6.0,>=4.1.0
  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
Requirement already satisfied: ipython<8.0,>=7.23.1 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (7.28.0)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (0.1.3)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (6.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (7.0.6)
Requirement already satisfied: backcall in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: colorama in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.4.4)
Requirement already satisfied: setuptools>=18.5 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (58.3.0)
Requirement already satisfied: pygments in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (2.10.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (3.0.21)
Requirement already satisfied: pickleshare in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.7.5)
Requirement already satisfied: decorator in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (5.1.0)
Requirement already satisfied: jedi>=0.16 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.8.2)
Requirement already satisfied: pyzmq>=13 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (22.3.0)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (4.8.1)
Requirement already satisfied: entrypoints in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (0.3)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (2.8.2)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (1.5.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\XXX\appdata\local\p
main.ts:291 install stderr: Requirement already satisfied: jupyter in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
Requirement already satisfied: notebook in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.5)
Requirement already satisfied: qtconsole in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (5.1.1)
Requirement already satisfied: jupyter-console in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.0)
Requirement already satisfied: ipywidgets in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (7.6.5)
Requirement already satisfied: ipykernel in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.4.2)
Requirement already satisfied: nbconvert in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.2.0)
Requirement already satisfied: ipython-genutils in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (0.2.0)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (1.5.1)
Requirement already satisfied: traitlets<6.0,>=4.1.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (5.1.0)
Collecting traitlets<6.0,>=4.1.0
  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
Requirement already satisfied: ipython<8.0,>=7.23.1 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (7.28.0)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (0.1.3)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (6.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->jupyter) (7.0.6)
Requirement already satisfied: backcall in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: colorama in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.4.4)
Requirement already satisfied: setuptools>=18.5 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (58.3.0)
Requirement already satisfied: pygments in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (2.10.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (3.0.21)
Requirement already satisfied: pickleshare in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.7.5)
Requirement already satisfied: decorator in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (5.1.0)
Requirement already satisfied: jedi>=0.16 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython<8.0,>=7.23.1->ipykernel->jupyter) (0.8.2)
Requirement already satisfied: pyzmq>=13 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (22.3.0)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (4.8.1)
Requirement already satisfied: entrypoints in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (0.3)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (2.8.2)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter) (1.5.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\XXX\appdata\local\p
```

**Comment by tillahoffmann** [comment]
The error message

```
import tornado.concurrent as tc
ModuleNotFoundError: No module named 'tornado.concurrent'
```
in https://github.com/tillahoffmann/obsidian-jupyter/issues/18#issuecomment-950321876 suggests that there's still an issue with your python environment. It's unfortunately something that's difficult to debug remotely.
