### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by reouvenzana** [tillahoffmann/obsidian-jupyter#6]
Hello, I've just created a Github account only for this plugin I've been dreaming of !

I'm a total beginner in the computer / mathematics fields and I hope I'm not doing anything wrong.

I'm on Windows and Python 3 is in my environment path.

![image](https://user-images.githubusercontent.com/90115772/132109422-a29be7e7-1b33-443f-8ae0-26c0f129d55e.png)

When I'm trying to run the code above, nothing happens. The console returns : 

```
python: can't open file
'xxx\Mathematics\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py'
```

I have Jupyer Notebooks installed, via Anaconda.

Thank you 😃

**Comment by ghost** [comment]
Download [obsidian-jupyter.py](https://github.com/tillahoffmann/obsidian-jupyter/find/master)
Copy it in .obsidian/plugins/obsidian-jupyter.

**Comment by reouvenzana** [comment]
Thank you for your help. I just did that, then installed some packages ( nbconvert, jupyter-client... ). The console is now returning :

```
 raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
```

I'v tried to run jupyter notebook at the same time but to no avail. I'm not sure what to do at this point.

Thank you very much.

**Comment by tillahoffmann** [comment]
@reouvenzana, could you post the full output from the console?

**Comment by reouvenzana** [comment]
Hello @tillahoffmann !

```
created new client for doc 93c4c2ebdc299f60
main.ts:43 INFO:obsidian-jupyter:started server for document 93c4c2ebdc299f60

main.ts:43 INFO:obsidian-jupyter:received request: {"id":"c8be19ca-883b-4b2b-9979-f5d9971f0295","body":{"command":"execute","source":"print(2+2)\n"}}


main.ts:43 WARNING:traitlets:Kernelspec name python3 cannot be found!

main.ts:43 Traceback (most recent call last):
  File "C:\Users\Reouv\OneDrive\Obsidian\Mathematics\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 45, in <module>

main.ts:43     nb = client.execute(nb)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 78, in wrapped

main.ts:43     return just_run(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 57, in just_run

main.ts:43     return loop.run_until_complete(coro)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete

main.ts:43     return future.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 542, in async_execute

main.ts:43     async with self.async_setup_kernel(**kwargs):
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 175, in __aenter__

main.ts:43     return await self.gen.__anext__()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 500, in async_setup_kernel

main.ts:43     await self.async_start_new_kernel(**kwargs)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 412, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result

main.ts:43     raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 331, in _async_start_kernel

main.ts:43     kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)

main.ts:43   File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 295, in _async_pre_start_kernel
    self.kernel_spec,
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 131, in kernel_spec

main.ts:43     self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\kernelspec.py", line 292, in get_kernel_spec

main.ts:43     raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3

main.ts:43 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Reouv\OneDrive\Obsidian\Mathematics\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 63, in <module>
    km.shutdown_kernel()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 433, in _async_shutdown_kernel

main.ts:43     await ensure_async(self.interrupt_kernel())
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result

main.ts:43     raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 541, in _async_interrupt_kernel

main.ts:43     raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!

```

**Comment by tillahoffmann** [comment]
It looks like you don't have a python kernel for jupyter installed. You can verify by running `jupyter kernelspec list`. The official documentation should be able to help with installing the kernel.

**Comment by reouvenzana** [comment]
Thank you. 

So :

I followed these steps : [Installing a Jupter Kernel](https://gdcoder.com/how-to-create-and-add-a-conda-environment-as-jupyter-kernel/)

Then, I still encountered an error ( DLL load fail... ) and the new kernel didn't work in Jupyter. I fixed this issue by installing jupyter notebook in the new environment ( which is not indicated in the link above ).

Now, my new kernel (Python obsidian) is correctly running in jupyter.

![image](https://user-images.githubusercontent.com/90115772/132217899-94cfb0b7-038f-4928-856b-ff3959797ace.png)

But it still doesn't work in Obsidian 😓

```
created new client for doc 910a50720a635b7d
main.ts:43 INFO:obsidian-jupyter:started server for document 910a50720a635b7d

main.ts:43 INFO:obsidian-jupyter:received request: {"id":"7aed6334-9153-4b91-8699-e137962c6d4f","body":{"command":"execute","source":"print(2+2)\n"}}


main.ts:43 WARNING:traitlets:Kernelspec name python3 cannot be found!

main.ts:43 Traceback (most recent call last):
  File "C:\Users\Reouv\OneDrive\Obsidian\Mathematics\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 45, in <module>
    nb = client.execute(nb)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 78, in wrapped

main.ts:43     return just_run(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete

main.ts:43     return future.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 542, in async_execute

main.ts:43     async with self.async_setup_kernel(**kwargs):
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 175, in __aenter__

main.ts:43     return await self.gen.__anext__()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 500, in async_setup_kernel

main.ts:43     await self.async_start_new_kernel(**kwargs)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 412, in async_start_new_kernel

main.ts:43     await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))

main.ts:43   File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result

main.ts:43     raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 331, in _async_start_kernel

main.ts:43     kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result

main.ts:43     raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 295, in _async_pre_start_kernel

main.ts:43     self.kernel_spec,
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 131, in kernel_spec

main.ts:43     self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\kernelspec.py", line 292, in get_kernel_spec

main.ts:43     raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3

main.ts:43 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Reouv\OneDrive\Obsidian\Mathematics\.obsidian\plugins\obsidian-jupyter\obsidian-jupyter.py", line 63, in <module>

main.ts:43     km.shutdown_kernel()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result

main.ts:43     raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 433, in _async_shutdown_kernel

main.ts:43     await ensure_async(self.interrupt_kernel())
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped

main.ts:43     return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete

main.ts:43     return f.result()
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step

main.ts:43     result = coro.send(None)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_client\manager.py", line 541, in _async_interrupt_kernel

main.ts:43     raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
```

Here are my current kernels :

```
Available kernels:
  obsidian    C:\Users\Reouv\AppData\Roaming\jupyter\kernels\obsidian
  python3     C:\Users\Reouv\anaconda3\share\jupyter\kernels\python3
```

Here's my Path variable :

![image](https://user-images.githubusercontent.com/90115772/132218410-f9d72742-3e89-47c0-a004-6bf64196cb18.png)

And the plugin settings :

![image](https://user-images.githubusercontent.com/90115772/132218465-ea9d6c2f-9273-4366-a9f1-3ae780cd2d38.png)

**Comment by tillahoffmann** [comment]
Obsidian may be using a different path variable than the standard console. Could you try using the full path to your python interpreter. If you don't know what the full path is, you can run `python -c 'import sys; print(sys.executable)'` to find out.

**Comment by reouvenzana** [comment]
Still not working. Same error ( I guess ).

**Comment by tillahoffmann** [comment]
Could you run the following from the windows command line and post the output? 

`curl -L https://bit.ly/3jTncQw | jupyter nbconvert --execute --stdin --stdout --to html --template basic`

**Comment by reouvenzana** [comment]
Hello,

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   233  100   233    0     0    233      0  0:00:01 --:--:--  0:00:01  1147
100   807  100   807    0     0    807      0  0:00:01 --:--:--  0:00:01   807
[NbConvertApp] Converting notebook into html
[NbConvertApp] WARNING | Kernelspec name python3 cannot be found!
Traceback (most recent call last):
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Reouv\AppData\Local\Programs\Python\Python39\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\nbconvertapp.py", line 522, in convert_notebooks
    self.convert_single_notebook("notebook.ipynb", input_buffer=input_buffer)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\nbconvertapp.py", line 483, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_file(input_buffer, resources=resources)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\exporters\html.py", line 129, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\exporters\templateexporter.py", line 374, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\exporters\exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\exporters\exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbconvert\preprocessors\execute.py", line 80, in preprocess
    with self.setup_kernel():
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 456, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 412, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 89, in ensure_async
    result = await obj
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 331, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 29, in ensure_async
    return await obj
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 295, in _async_pre_start_kernel
    self.kernel_spec,
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 131, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "c:\users\reouv\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\kernelspec.py", line 292, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
```
I don't know if it is necessary, but here are my environments : 

```
# conda environments:
#
base                  *  C:\Users\Reouv\anaconda3
obsidian                 C:\Users\Reouv\anaconda3\envs\obsidian
```
And, again, my jupyter kernels :
```
Available kernels:
  obsidian    C:\Users\Reouv\AppData\Roaming\jupyter\kernels\obsidian
  python3     C:\Users\Reouv\anaconda3\share\jupyter\kernels\python3
```

Thank you

**Comment by tillahoffmann** [comment]
Hm, this is a problem with your jupyter setup. Difficult to debug, but it seems like your paths don't match up. The `jupyter_client` package is installed under `c:\users\reouv\appdata\local\programs\python\python39`, but the conda environment is under `C:\Users\Reouv\anaconda3`.

**Comment by reouvenzana** [comment]
Thank you for your help. I'll just stop bothering you now and try to fix this by myself. I'll close the issue since it is not related anymore to your plugin.

**Comment by tillahoffmann** [comment]
Best of luck getting it sorted!
