### ISSUE TITLE
Missing Template subdirectory

### ISSUE THREAD

**Issue by mauf3r** [tillahoffmann/obsidian-jupyter#63]
Hi,

I just install the plugin, an I don't seem to be able to get ist running.

Environment: MacOS Ventura, Obsidian 1.1.15, Python 3.10.9

What I did:
- installed the Plugin
- ran "Install dependencies"
- Run test

Console-Output ends with an error on a missing template directory. I tried to create it manually, but the error remains the same:
`
mkdir -p /Users/maufer/Library/Python/3.10/share/jupyter/basic
`

Console output:

```
created new client for doc test-document using interpreter /opt/homebrew/bin/python3
plugin:obsidian-jupyter:3146 INFO:obsidian-jupyter:started server for document test-document

plugin:obsidian-jupyter:3146 INFO:obsidian-jupyter:received request: {"id":"5f411dab-ff06-4019-9088-24d09c759737","body":{"command":"execute","source":"1 + 1"}}


plugin:obsidian-jupyter:3146 INFO:traitlets:Executing notebook with kernel: 

plugin:obsidian-jupyter:3146 INFO:obsidian-jupyter:shutting down kernel...

plugin:obsidian-jupyter:3146 Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 656, in get

plugin:obsidian-jupyter:3146     value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maufer/Library/Mobile Documents/iCloud~md~obsidian/Documents/Zettelkasten/.obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py", line 45, in <module>

plugin:obsidian-jupyter:3146     html_exporter = HTMLExporter(template_name='basic')
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 348, in __init__

plugin:obsidian-jupyter:3146     super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 122, in __init__

plugin:obsidian-jupyter:3146     self._init_preprocessors()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 528, in _init_preprocessors

plugin:obsidian-jupyter:3146     conf = self._get_conf()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 546, in _get_conf

plugin:obsidian-jupyter:3146     for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 659, in get

plugin:obsidian-jupyter:3146     default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults

plugin:obsidian-jupyter:3146     return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1233, in __call__

plugin:obsidian-jupyter:3146     return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 557, in _template_paths

plugin:obsidian-jupyter:3146     template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 642, in get_template_names

plugin:obsidian-jupyter:3146     raise ValueError(
ValueError: No template sub-directory with name 'basic' found in the following paths:
	/Users/maufer/Library/Jupyter
	/Users/maufer/Library/Python/3.10/share/jupyter
	/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter

```

**Comment by wjixiang** [comment]
pip install --upgrade jupyter
